# Generated by Django 6.0.3 on 2026-03-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(upload_to='ticafe/media/categorias/'),
        ),
    ]
